CREATE DATABASE NYC_SHOOTINGS;
USE NYC_SHOOTINGS;

SELECT * FROM RAW_NYC_SHOOTINGS;

SELECT COUNT(*) FROM RAW_NYC_SHOOTINGS;

SELECT DISTINCT BORO FROM RAW_NYC_SHOOTINGS;

SELECT DISTINCT LOC_OF_OCCUR_DESC FROM RAW_NYC_SHOOTINGS;

SELECT DISTINCT LOC_CLASSFCTN_DESC FROM RAW_NYC_SHOOTINGS;

SELECT DISTINCT PRECINCT FROM RAW_NYC_SHOOTINGS;

SELECT DISTINCT LOCATION_DESC FROM RAW_NYC_SHOOTINGS;

-- NO DUPLICATE ROWS
WITH CTE AS(
SELECT *, ROW_NUMBER() OVER (PARTITION BY OCCUR_DATE,OCCUR_TIME,BORO,LOC_OF_OCCUR_DESC,PRECINCT,JURISDICTION_CODE,LOC_CLASSFCTN_DESC,LOCATION_DESC,X_COORD_CD,Y_COORD_CD,LATITUDE,LONGITUDE ORDER BY INCIDENT_KEY) RN
FROM RAW_NYC_SHOOTINGS)
SELECT * FROM CTE WHERE RN >=2;

--Out of 24127 recorded shootings, 85.8% occured outside and 14.2% occured inside.
SELECT 
'Shooting Occurance Rate' as ' ',
ROUND(SUM(CASE WHEN LOC_OF_OCCUR_DESC = 'OUTSIDE' THEN 1 ELSE 0 END)*100.0,2)/COUNT(*) 'Outside',
ROUND(SUM(CASE WHEN LOC_OF_OCCUR_DESC = 'INSIDE' THEN 1 ELSE 0 END)*100.0,2)/COUNT(*) 'Inside'
FROM RAW_NYC_SHOOTINGS;

-- Total Shootings per borough
SELECT BORO, COUNT(*) 'TOTAL SHOOTINGS' FROM RAW_NYC_SHOOTINGS
GROUP BY BORO
ORDER BY COUNT(*) DESC;

-- % of shootings per borough
SELECT 
BORO,
FORMAT(ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM RAW_NYC_Shootings),2),'N2')
FROM RAW_NYC_SHOOTINGS
GROUP BY BORO;

SELECT
ROUND(SUM(CASE WHEN BORO = 'BROOKLYN' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS B_C,
ROUND(SUM(CASE WHEN BORO = 'BRONX' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS BX_C,
ROUND(SUM(CASE WHEN BORO = 'MANHATTAN' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS M_C,
ROUND(SUM(CASE WHEN BORO = 'STATEN ISLAND' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS SI_C,
ROUND(SUM(CASE WHEN BORO = 'QUEENS' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS Q_C
FROM RAW_NYC_Shootings

--SHOOTING OCCURRANCE RATE PER BOROUGH PER YEAR
WITH CTE AS (
SELECT 
BORO, YEAR(OCCUR_DATE) YR, COUNT(*) TOTAL_SHOOTINGS,
FORMAT(ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM RAW_NYC_Shootings),2),'N2') AS SOR
FROM RAW_NYC_SHOOTINGS
GROUP BY BORO, YEAR(OCCUR_DATE)
)
SELECT *,
FORMAT(ROUND((1.0*TOTAL_SHOOTINGS - LAG(TOTAL_SHOOTINGS,1) OVER (PARTITION BY BORO ORDER BY YR))/LAG(TOTAL_SHOOTINGS,1) OVER (PARTITION BY BORO ORDER BY YR)*100.0,2),'N2')
FROM CTE
WHERE YR != 2026;

-- Year over Year Shooting Growth (%)
SELECT 
	YEAR(OCCUR_DATE) AS 'YEAR',
	COUNT(*) 'TOTAL SHOOTINGS',
	SUM(COUNT(*)) OVER (ORDER BY YEAR(OCCUR_DATE)) AS 'RUNNING TOTAL SHOOTINGS',
	((COUNT(*)*1.0-LAG(COUNT(*),1) OVER (ORDER BY YEAR(OCCUR_DATE)))/LAG(COUNT(*),1) OVER (ORDER BY YEAR(OCCUR_DATE)))*100 AS 'YoY Growth Rate %'
FROM RAW_NYC_SHOOTINGS
WHERE YEAR(OCCUR_DATE) != 2026
GROUP BY YEAR(OCCUR_DATE)
ORDER BY YEAR(OCCUR_DATE);

-- # Of shootings per parts of the day
SELECT 
SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 5 and 11 THEN 1 ELSE 0 END) AS MORNING,
SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 12 AND 16 THEN 1 ELSE 0 END) AS AFTERNOON,
SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 17 AND 21 THEN 1 ELSE 0 END) AS EVENING,
SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) IN (0,1,2,3,4,22,23) THEN 1 ELSE 0 END) AS NIGHT
FROM RAW_NYC_Shootings

--Shooting Occurance Rate per parts of the day
SELECT 
ROUND(SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 5 and 11 THEN 1 ELSE 0 END)*100.0/count(*),2) AS MORNING,
ROUND(SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 12 AND 16 THEN 1 ELSE 0 END)*100.0/count(*),2)  AS AFTERNOON,
ROUND(SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) BETWEEN 17 AND 21 THEN 1 ELSE 0 END)*100.0/count(*),2)  AS EVENING,
ROUND(SUM(CASE WHEN DATEPART(HOUR,OCCUR_TIME) IN (0,1,2,3,4,22,23) THEN 1 ELSE 0 END)*100.0/count(*),2)  AS NIGHT
FROM RAW_NYC_Shootings

